apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-gateway.yaml
  - payment-orchestrator.yaml
  - fraud-detection.yaml
  - payment-processor.yaml
  - settlement-service.yaml
  - notification-service.yaml
