apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-service
  namespace: payflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement-service
  template:
    metadata:
      labels:
        app: settlement-service
    spec:
      containers:
        - name: settlement-service
          image: payflow-ruby-settlement-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: payflow-secret
                  key: DATABASE_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: settlement-service
  namespace: payflow
spec:
  selector:
    app: settlement-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
