apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: payflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator
          image: payflow/traffic-generator:latest
          env:
            - name: GATEWAY_URL
              value: http://api-gateway:8080
            - name: REQUESTS_PER_SECOND
              value: "10"
            - name: CONCURRENCY
              value: "5"
