apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: payflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: payflow/notification-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
          envFrom:
            - configMapRef:
                name: payflow-config
            - secretRef:
                name: payflow-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
