apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: payflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: payflow/notification-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8085
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: payflow-secrets
                  key: DATABASE_URL
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: payflow-config
                  key: KAFKA_BROKERS
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
