apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  namespace: payflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - name: payment-processor
          image: payflow/payment-processor:latest
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: payflow-config
                  key: PORT_PROCESSOR
            - name: GATEWAY_STUB_URL
              valueFrom:
                configMapKeyRef:
                  name: payflow-config
                  key: GATEWAY_STUB_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: payflow
spec:
  selector:
    app: payment-processor
  ports:
    - port: 8083
      targetPort: 8083
